import { io as Client } from 'socket.io-client';
const URL = 'http://127.0.0.1:3106';
const ok = (n: string, c: boolean) => { console.log(`${c ? 'PASS' : 'FAIL'}  ${n}`); if (!c) process.exitCode = 1; };
const emit = <T,>(s: any, ev: string, d?: unknown): Promise<T> => new Promise(r => d === undefined ? s.emit(ev, r) : s.emit(ev, d, r));
const host = Client(URL), guest = Client(URL);
await new Promise(r => host.on('connect', r)); await new Promise(r => guest.on('connect', r));
const c: any = await emit(host, 'room:create', { playerName: 'A', gender: 'F' });
await emit(guest, 'room:join', { code: c.room.code, playerName: 'B', gender: 'M' });
guest.emit('room:accept-settings'); await new Promise(r => setTimeout(r, 300));
let reveal: any = null; host.on('game:reveal', (d: any) => { reveal = d; });
await emit(host, 'game:start'); await new Promise(r => setTimeout(r, 4000));
const p: any = await emit(host, 'game:answer', { answer: 'passer' });
ok('passer accepte par le serveur', p?.accepted === true);
await emit(guest, 'game:answer', { answer: 'une vraie reponse' });
await new Promise(r => setTimeout(r, 1500));
ok('reveal recu', !!reveal);
ok('passer = exactement 0 point', reveal?.points1 === 0);
host.close(); guest.close(); process.exit(process.exitCode ?? 0);
